# Generated by Django 5.1.2 on 2025-01-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'None'), (1, 'LEVEL 1'), (2, 'LEVEL 2'), (3, 'LEVEL 3')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
