# Generated by Django 5.1.2 on 2025-01-05 16:52

import DHT._models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_alter_user_level_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', DHT._models.user.CustomUserManager()),
            ],
        ),
    ]
