# Generated by Django 5.1.2 on 2025-01-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_alter_dht11_hum_alter_dht11_temp_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
